sesame_site_homepage:
    path:     /
    defaults: { _controller: SesameSiteBundle:Hp:index }

sesame_site_page_index:
    path:     /pages/
    defaults: { _controller: SesameSiteBundle:Page:list }
        
sesame_site_sitemap:
    path:     /plan-de-site.{_format}
    defaults: { _controller: SesameSiteBundle:Page:list, _format: html }
        # _format:    html|rss|xml
    
sesame_site_page_show:
    path:     /pages/{slug}.{id}.html
    defaults: { _controller: SesameSiteBundle:Page:view }
    requirements:
        # slug:   \w+
        id:     \d+
        
sesame_site_robots:
    path:     /robots.txt
    defaults: { _controller: SesameSiteBundle:Widget:robots}
    
gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /photos/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /photos/
        
sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin
    
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin/

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin/
    
sonata_user_security:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_security_1.xml"

sonata_user_resetting:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_resetting_1.xml"
    prefix: /resetting

sonata_user_profile:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_profile_1.xml"
    prefix: /profile

sonata_user_register:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_registration_1.xml"
    prefix: /register

sonata_user_change_password:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_change_password_1.xml"
    prefix: /profile