parameters:
    # ... other parameters
    security.acl.permission.map.class: Sonata\AdminBundle\Security\Acl\Permission\AdminPermissionMap
    # optionally use a custom MaskBuilder
    #sonata.admin.security.mask.builder.class: Sonata\AdminBundle\Security\Acl\Permission\MaskBuilder

services:
#    sesame_site.example:
#        class: %sesame_site.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    sonata.admin.page:
        class: Sesame\SiteBundle\Admin\PageAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Contenu", label: "Pages" }
        arguments:
            - ~
            - Sesame\SiteBundle\Entity\Page
            - ~
        calls:
            - [ setTranslationDomain, [SesameSiteBundle]]
            
    sonata.admin.site:
        class: Sesame\SiteBundle\Admin\SiteAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Contenu", label: "Site" }
        arguments:
            - ~
            - Sesame\SiteBundle\Entity\Site
            - ~
        calls:
            - [ setTranslationDomain, [SesameSiteBundle]]
            
    # gedmo.listener.tree:
        # class: Gedmo\Tree\TreeListener
        # tags:
            # - { name: doctrine.event_subscriber, connection: default }
        # calls:
            # - [ setAnnotationReader, [ @annotation_reader ] ]

    gedmo.listener.timestampable:
        class: Gedmo\Timestampable\TimestampableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ @annotation_reader ] ]