parameters:
#    sesame_site.example.class: Sesame\SiteBundle\Example

services:
#    sesame_site.example:
#        class: %sesame_site.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
