#!/bin/bash
# git pull
# php composer.phar update -n
/usr/bin/php5 composer.phar -vvv update
# /usr/bin/php5 app/console doctrine:schema:validate
# /usr/bin/php5 app/console
# php -f app/console doctrine:schema:update --dump-sql
# php -f app/console doctrine:schema:update --force
# php -f app/console doctrine:schema:validate
# php -f app/console asset:install
# php -f app/console cache:clear --no-warmup
# php -f app/console doctrine:mapping:info
# php -f app/console cache:clear --env=prod

