<?php

namespace Sesame\SiteBundle\Entity;

use Doctrine\ORM\EntityRepository;
// use Gedmo\Tree\Entity\Repository\NestedTreeRepository;
// use Doctrine\ORM\Query;
// use Sesame\SiteBundle\Entity\Site;
// use Closure;

/**
 * SiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SiteRepository extends EntityRepository
{
}

