sonata_admin:
    title:      Acme Demo Bundle
    title_logo: bundles/acmedemo/img/fancy_acme_logo.png
    
    security:
        handler: sonata.admin.security.handler.acl
        # acl security information
        information:
            GUEST:    [VIEW, LIST]
            STAFF:    [EDIT, LIST, CREATE]
            EDITOR:   [OPERATOR, EXPORT]
            ADMIN:    [MASTER]
        # permissions not related to an object instance and also to be available when objects do not exist
        # the DELETE admin permission means the user is allowed to batch delete objects
        admin_permissions: [CREATE, LIST, DELETE, UNDELETE, EXPORT, OPERATOR, MASTER]
        # permission related to the objects
        object_permissions: [VIEW, EDIT, DELETE, UNDELETE, OPERATOR, MASTER, OWNER]
        
    templates:
        layout:  SonataAdminBundle::standard_layout.html.twig
        ajax:    SonataAdminBundle::ajax_layout.html.twig
        list:    SonataAdminBundle:CRUD:list.html.twig
        show:    SonataAdminBundle:CRUD:show.html.twig
        edit:    SonataAdminBundle:CRUD:edit.html.twig
        history: SonataAdminBundle:CRUD:history.html.twig
        preview: SonataAdminBundle:CRUD:preview.html.twig
        delete:  SonataAdminBundle:CRUD:delete.html.twig
        batch:   SonataAdminBundle:CRUD:list__batch.html.twig
        acl:     SonataAdminBundle:CRUD:acl.html.twig
        action:  SonataAdminBundle:CRUD:action.html.twig
        select:  SonataAdminBundle:CRUD:list__select.html.twig
        dashboard:           SonataAdminBundle:Core:dashboard.html.twig
        search:              SonataAdminBundle:Core:search.html.twig
        batch_confirmation:  SonataAdminBundle:CRUD:batch_confirmation.html.twig
        inner_list_row:      SonataAdminBundle:CRUD:list_inner_row.html.twig
        base_list_field:     SonataAdminBundle:CRUD:base_list_field.html.twig
        list_block:          SonataAdminBundle:Block:block_admin_list.html.twig
        user_block:          SonataAdminBundle:Core:user_block.html.twig
        pager_links:         SonataAdminBundle:Pager:links.html.twig
        pager_results:       SonataAdminBundle:Pager:results.html.twig
        history_revision_timestamp:  SonataAdminBundle:CRUD:history_revision_timestamp.html.twig
        short_object_description:    SonataAdminBundle:Helper:short-object-description.html.twig
        search_result_block: SonataAdminBundle:Block:block_search_result.html.twig